# Train and Test Split

## Import the relevant libraries 

In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

## Generate some data we are going to split

In [5]:
a = np.arange(1,101)

In [6]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

## Split the data

In [8]:
train_test_split(a)

[array([99, 10, 57, 79, 90, 20, 93, 21, 55, 87, 25,  9, 38, 52,  2, 15, 76,
        95, 59, 30,  1, 35, 84, 61, 24, 66, 22, 97, 88, 29, 67, 58, 19, 17,
        36, 70, 86, 37, 32, 91, 45, 98,  6, 49, 41, 40, 13, 89, 11, 23, 68,
        42, 92, 39,  4,  7, 83, 12, 31, 69, 44, 65, 54, 62, 71, 26, 43, 18,
        63, 60, 53, 33,  5, 50,  8]),
 array([ 94, 100,   3,  27,  72,  28,  80,  75,  51,  85,  16,  78,  56,
         46,  77,  48,  82,  64,  81,  47,  74,  34,  96,  14,  73])]

In [26]:
a_train, a_test= train_test_split(a,test_size=0.2,shuffle=False,random_state=42)

In [40]:
b_train,b_test=train_test_split(b,test_size=0.2,shuffle=False)

## Explore the result

In [41]:
a_train.shape,a_test.shape

((80,), (20,))

In [42]:
a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [43]:
a_test

array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100])

In [44]:
b_train.shape,b_test.shape

((80,), (20,))

In [45]:
b_train

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580])

In [46]:
b_test

array([581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593,
       594, 595, 596, 597, 598, 599, 600])